//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerManagementClient.ConsumerManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consumer", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService.Model")]
    [System.SerializableAttribute()]
    public partial class Consumer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BillAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ConsumerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BillAmount {
            get {
                return this.BillAmountField;
            }
            set {
                if ((this.BillAmountField.Equals(value) != true)) {
                    this.BillAmountField = value;
                    this.RaisePropertyChanged("BillAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ConsumerID {
            get {
                return this.ConsumerIDField;
            }
            set {
                if ((this.ConsumerIDField.Equals(value) != true)) {
                    this.ConsumerIDField = value;
                    this.RaisePropertyChanged("ConsumerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
    [System.SerializableAttribute()]
    public partial class ConsumerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consumerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billAmount {
            get {
                return this.billAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.billAmountField, value) != true)) {
                    this.billAmountField = value;
                    this.RaisePropertyChanged("billAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string consumerID {
            get {
                return this.consumerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.consumerIDField, value) != true)) {
                    this.consumerIDField = value;
                    this.RaisePropertyChanged("consumerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.dueDateField, value) != true)) {
                    this.dueDateField = value;
                    this.RaisePropertyChanged("dueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService.Model")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumerManagementService.IConsumerManagementService")]
    public interface IConsumerManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/add", ReplyAction="http://tempuri.org/IConsumerManagementService/addResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/addConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        int add(ConsumerManagementClient.ConsumerManagementService.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/add", ReplyAction="http://tempuri.org/IConsumerManagementService/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(ConsumerManagementClient.ConsumerManagementService.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerID", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getConsumerIDConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerID", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerIDResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameLikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameLikeConsumerFau" +
            "ltFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerFirstNameLike(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameLikeResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerFirstNameLikeAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerFirstName", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameResponse")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerFirstName(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerFirstName", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerFirstNameResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerFirstNameAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerLastLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerLastLikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getConsumerLastLikeConsumerFaultFau" +
            "lt", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerLastLike(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerLastLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerLastLikeResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerLastLikeAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerLastName", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerLastNameResponse")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerLastName(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerLastName", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerLastNameResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerLastNameAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerCityLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerCityLikeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getConsumerCityLikeConsumerFaultFau" +
            "lt", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerCityLike(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerCityLike", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerCityLikeResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerCityLikeAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerCity", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerCityResponse")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerCity(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerCity", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerCityResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerCityAsync(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getDefaulter", ReplyAction="http://tempuri.org/IConsumerManagementService/getDefaulterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getDefaulterConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getDefaulter(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getDefaulter", ReplyAction="http://tempuri.org/IConsumerManagementService/getDefaulterResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getDefaulterAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getRegular", ReplyAction="http://tempuri.org/IConsumerManagementService/getRegularResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getRegularConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getRegular(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getRegular", ReplyAction="http://tempuri.org/IConsumerManagementService/getRegularResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getRegularAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerByBA", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerByBAResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/getConsumerByBAConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerByBA(string billAmount, string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getConsumerByBA", ReplyAction="http://tempuri.org/IConsumerManagementService/getConsumerByBAResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerByBAAsync(string billAmount, string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/updateConsumer", ReplyAction="http://tempuri.org/IConsumerManagementService/updateConsumerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/updateConsumerConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        int updateConsumer(ConsumerManagementClient.ConsumerManagementService.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/updateConsumer", ReplyAction="http://tempuri.org/IConsumerManagementService/updateConsumerResponse")]
        System.Threading.Tasks.Task<int> updateConsumerAsync(ConsumerManagementClient.ConsumerManagementService.Consumer consumer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getAll", ReplyAction="http://tempuri.org/IConsumerManagementService/getAllResponse")]
        ConsumerManagementClient.ConsumerManagementService.Consumer[] getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getAll", ReplyAction="http://tempuri.org/IConsumerManagementService/getAllResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/deleteID", ReplyAction="http://tempuri.org/IConsumerManagementService/deleteIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/deleteIDConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        int deleteID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/deleteID", ReplyAction="http://tempuri.org/IConsumerManagementService/deleteIDResponse")]
        System.Threading.Tasks.Task<int> deleteIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getAllLogin", ReplyAction="http://tempuri.org/IConsumerManagementService/getAllLoginResponse")]
        ConsumerManagementClient.ConsumerManagementService.Login[] getAllLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/getAllLogin", ReplyAction="http://tempuri.org/IConsumerManagementService/getAllLoginResponse")]
        System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Login[]> getAllLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/updatePassword", ReplyAction="http://tempuri.org/IConsumerManagementService/updatePasswordResponse")]
        int updatePassword(ConsumerManagementClient.ConsumerManagementService.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/updatePassword", ReplyAction="http://tempuri.org/IConsumerManagementService/updatePasswordResponse")]
        System.Threading.Tasks.Task<int> updatePasswordAsync(ConsumerManagementClient.ConsumerManagementService.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/addLogin", ReplyAction="http://tempuri.org/IConsumerManagementService/addLoginResponse")]
        int addLogin(ConsumerManagementClient.ConsumerManagementService.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/addLogin", ReplyAction="http://tempuri.org/IConsumerManagementService/addLoginResponse")]
        System.Threading.Tasks.Task<int> addLoginAsync(ConsumerManagementClient.ConsumerManagementService.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/authenticate", ReplyAction="http://tempuri.org/IConsumerManagementService/authenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsumerManagementClient.ConsumerManagementService.ConsumerFault), Action="http://tempuri.org/IConsumerManagementService/authenticateConsumerFaultFault", Name="ConsumerFault", Namespace="http://schemas.datacontract.org/2004/07/ConsumerManagementService")]
        int authenticate(ConsumerManagementClient.ConsumerManagementService.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerManagementService/authenticate", ReplyAction="http://tempuri.org/IConsumerManagementService/authenticateResponse")]
        System.Threading.Tasks.Task<int> authenticateAsync(ConsumerManagementClient.ConsumerManagementService.Login login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsumerManagementServiceChannel : ConsumerManagementClient.ConsumerManagementService.IConsumerManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsumerManagementServiceClient : System.ServiceModel.ClientBase<ConsumerManagementClient.ConsumerManagementService.IConsumerManagementService>, ConsumerManagementClient.ConsumerManagementService.IConsumerManagementService {
        
        public ConsumerManagementServiceClient() {
        }
        
        public ConsumerManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsumerManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add(ConsumerManagementClient.ConsumerManagementService.Consumer consumer) {
            return base.Channel.add(consumer);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(ConsumerManagementClient.ConsumerManagementService.Consumer consumer) {
            return base.Channel.addAsync(consumer);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerID(string id) {
            return base.Channel.getConsumerID(id);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerIDAsync(string id) {
            return base.Channel.getConsumerIDAsync(id);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerFirstNameLike(string strName) {
            return base.Channel.getConsumerFirstNameLike(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerFirstNameLikeAsync(string strName) {
            return base.Channel.getConsumerFirstNameLikeAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerFirstName(string strName) {
            return base.Channel.getConsumerFirstName(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerFirstNameAsync(string strName) {
            return base.Channel.getConsumerFirstNameAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerLastLike(string strName) {
            return base.Channel.getConsumerLastLike(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerLastLikeAsync(string strName) {
            return base.Channel.getConsumerLastLikeAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerLastName(string strName) {
            return base.Channel.getConsumerLastName(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerLastNameAsync(string strName) {
            return base.Channel.getConsumerLastNameAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerCityLike(string strName) {
            return base.Channel.getConsumerCityLike(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerCityLikeAsync(string strName) {
            return base.Channel.getConsumerCityLikeAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerCity(string strName) {
            return base.Channel.getConsumerCity(strName);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerCityAsync(string strName) {
            return base.Channel.getConsumerCityAsync(strName);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getDefaulter(System.DateTime date) {
            return base.Channel.getDefaulter(date);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getDefaulterAsync(System.DateTime date) {
            return base.Channel.getDefaulterAsync(date);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getRegular(System.DateTime date) {
            return base.Channel.getRegular(date);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getRegularAsync(System.DateTime date) {
            return base.Channel.getRegularAsync(date);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getConsumerByBA(string billAmount, string condition) {
            return base.Channel.getConsumerByBA(billAmount, condition);
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getConsumerByBAAsync(string billAmount, string condition) {
            return base.Channel.getConsumerByBAAsync(billAmount, condition);
        }
        
        public int updateConsumer(ConsumerManagementClient.ConsumerManagementService.Consumer consumer) {
            return base.Channel.updateConsumer(consumer);
        }
        
        public System.Threading.Tasks.Task<int> updateConsumerAsync(ConsumerManagementClient.ConsumerManagementService.Consumer consumer) {
            return base.Channel.updateConsumerAsync(consumer);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Consumer[] getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Consumer[]> getAllAsync() {
            return base.Channel.getAllAsync();
        }
        
        public int deleteID(string id) {
            return base.Channel.deleteID(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteIDAsync(string id) {
            return base.Channel.deleteIDAsync(id);
        }
        
        public ConsumerManagementClient.ConsumerManagementService.Login[] getAllLogin() {
            return base.Channel.getAllLogin();
        }
        
        public System.Threading.Tasks.Task<ConsumerManagementClient.ConsumerManagementService.Login[]> getAllLoginAsync() {
            return base.Channel.getAllLoginAsync();
        }
        
        public int updatePassword(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.updatePassword(login);
        }
        
        public System.Threading.Tasks.Task<int> updatePasswordAsync(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.updatePasswordAsync(login);
        }
        
        public int addLogin(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.addLogin(login);
        }
        
        public System.Threading.Tasks.Task<int> addLoginAsync(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.addLoginAsync(login);
        }
        
        public int authenticate(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.authenticate(login);
        }
        
        public System.Threading.Tasks.Task<int> authenticateAsync(ConsumerManagementClient.ConsumerManagementService.Login login) {
            return base.Channel.authenticateAsync(login);
        }
    }
}
